name: Deploy Javadoc

permissions:
  contents: write

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc to GitHub Pages
        uses: dev-vince/actions-publish-javadoc@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          java-version: "17"
          java-distribution: "adopt"
          project: maven
          branch: "gh-pages"
